site_name: Thinking in Types
docs_dir: Chapters
site_url: https://ThinkingInTypes.github.io
repo_url: https://github.com/ThinkingInTypes/ThinkingInTypes.github.io

theme:
  name: material
  favicon: img/favicon.png
  features:
    - content.code.copy
    - content.code.select
    - navigation.indexes  # Ensures only one entry in TOC
    # - toc.integrate  # Makes TOC part of the left-hand navigation

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"


nav:
  - 01_Preface.md
  - 02_Foundations.md
  - 03_What_is_a_Type.md
  - 04_Basic_Annotations.md
  - 05_Collections.md
  - 06_Generics.md
  - 07_Dataclasses.md
  - 08_Callables.md
  - 09_Structural_Typing.md
  - 10_Specialized_Tools.md
  - 11_Make_Illegal_Types_Unrepresentable.md
  - 12_Errors_As_Values.md
  - 13_Pattern_Matching.md
  - 14_Advanced_Concepts.md
  - 15_Async.md
  - 16_Interoperability_and_Typing_Stubs.md
  - 17_Best_Practices.md
  - A1_Quick_Reference.md
  - A2_Glossary.md
  - A3_Type_Checkers.md
  - A4_Class_Attributes.md
